jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
        no_extensions: ''
      Python36:
        python.version: '3.6'
        no_extensions: ''
      Python37:
        python.version: '3.7'
        no_extensions: ''

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install -- upgrade pip
    displayName: "Update pip"

  - script: |
      make cythonize
    condition: eq(variables['no_extensions'], '')
    displayName: "Cythonize"

  - script: |
      pip install -r requirements/dev.txt
    displayName: 'Install dependencies'
    env:
      YARL_NO_EXTENSIONS: '$(no_extensions)'

  - script: |
      pip install pytest
      pytest tests --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
